apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: vkolmakov/auth
                  env:
                      - name: JWT_KEY # name of the env variable as we want to access it
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret # name of the secret
                                key: JWT_KEY # name of the key inside of the secret
---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    type: ClusterIP
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 3000
          targetPort: 3000
