apiVersion: apps/v1
kind: Deployment
metadata:
    name: expiration-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: expiration
    template:
        metadata:
            labels:
                app: expiration
        spec:
            containers:
                - name: expiration
                  image: vkolmakov/expiration
                  env:
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name # will use the pod ID as an identifier for the nats client
                      - name: NATS_URL
                        value: "http://nats-srv:4222"
                      - name: NATS_CLUSTER_ID
                        value: ticketing
                      - name: REDIS_HOST
                        value: expiration-redis-srv
