apiVersion: apps/v1
kind: Deployment
metadata:
    name: tickets-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tickets
    template:
        metadata:
            labels:
                app: tickets
        spec:
            containers:
                - name: tickets
                  image: vkolmakov/tickets
                  env:
                      - name: MONGO_URI
                        value: "mongodb://tickets-mongo-srv:27017/tickets" # note - if connection string contains any secrets, make sure to declare it as a secret, like JWT_KEY
                      - name: JWT_KEY # name of the env variable as we want to access it
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret # name of the secret
                                key: JWT_KEY # name of the key inside of the secret
---
apiVersion: v1
kind: Service
metadata:
    name: tickets-srv
spec:
    type: ClusterIP
    selector:
        app: tickets
    ports:
        - name: tickets
          protocol: TCP
          port: 3000
          targetPort: 3000
